const NewApplicationActionTypes = {
  NEW_APPLICATION_START: "NEW_APPLICATION_START",
  NEW_APPLICATION_SUCCESS: "NEW_APPLICATION_SUCCESS",
  NEW_APPLICATION_FAILURE: "NEW_APPLICATION_FAILURE",
};

export default NewApplicationActionTypes;
